---
namespace: centriascolocation

name: ansible_collection_aws

version: 1.0.0

readme: README.md

authors:
  - Michael Krieg <michael@centrias.de>
  - Dirk Piethan <dirk@centrias.de>
  - Volker Bohne <volker@centrias.de>

description: Reusable Ansible Roles to cover various requirements of installing AWS Agents on EC2 instances.

license:
  - Apache-2.0

tags:
  - aws
  - ec2
  - docker
  - ansible

dependencies: {}

repository: https://github.com/centriascolocation/ansible_collection_aws

documentation: https://github.com/centriascolocation/ansible_collection_aws

homepage: https://www.centrias.de

issues: https://github.com/centriascolocation/ansible_collection_aws/issues

build_ignore:
  - molecule
  - .DS_Store
