---

- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Check aws in PATH
      stat:
        path: /usr/local/bin/aws
      register: awscli

    - name: Check version
      ansible.builtin.shell: AWS_PAGER="" aws --version
      register: awscliversion
      changed_when: false

    - name: awscli is installed
      assert:
        that:
          - awscli.stat.exists
          - awscli.stat.executable
        fail_msg: "aws is NOT installed"
        success_msg: "aws is installed and executable"

    - name: verify version 2
      assert:
        that:
          - awscliversion.stdout is regex("^aws\-cli\/2\.\d+")
        fail_msg: "version seems incorrect"
        success_msg: "version is 2"

    - name: Check awscli (v1) pip installation
      ansible.builtin.shell: pip freeze
      register: pipfreeze
      changed_when: false

    - name: verify version 1 is no more installed
      assert:
        that:
          - pipfreeze.stdout is not regex("awscli")
        fail_msg: "please make sure to remove awscli via pip"
        success_msg: "no awscli pip package found"
